// Vendor every webfont the app uses into `static/fonts/` so the APK never touches
// the network for text or icons.
//
// Why this exists: the app used to <link> Google Fonts from `app.html`. On a poor
// connection (or fully offline) the Material Symbols font never arrived, so every
// icon fell back to rendering its *ligature name* as literal text — the spinner
// became the word "progress_activity" rotating on screen, and the Arabic fallback
// font's different metrics made labels overlap. Bundled fonts cannot fail.
//
// Run `npm run fonts` after adding a new icon name to `ICONS` below. The generated
// files are committed; the build itself never hits the network.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'static', 'fonts');
const CSS_OUT = join(ROOT, 'src', 'lib', 'fonts.css');
// Record of which icons the vendored font actually contains. `npm run icons:check`
// compares it against ICONS below, so editing the list without re-running this
// script fails the build instead of shipping an icon that renders as its own name.
const MANIFEST_OUT = join(OUT_DIR, 'icons.json');

// A modern desktop UA is required or Google serves the much larger .ttf format.
const UA =
	'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/**
 * Every icon the UI can render, including the ones chosen at runtime (ternaries,
 * tab configs, `icon=` props). Subsetting to just these keeps the icon font at a
 * few tens of KB instead of ~4 MB.
 *
 * Keep sorted. If an icon renders as a word in the app, it is missing from here.
 */
const ICONS = [
	'add',
	'arrow_back',
	'arrow_forward',
	'assignment',
	'calendar_clock',
	'calendar_month',
	'calendar_view_month',
	'cancel',
	'check',
	'check_circle',
	'chevron_left',
	'chevron_right',
	'close',
	'cloud_done',
	'cloud_off',
	'cloud_upload',
	'dashboard',
	'delete',
	'done_all',
	'download',
	'edit_note',
	'error',
	'event_available',
	'event_busy',
	'event_upcoming',
	'expand_less',
	'expand_more',
	'fact_check',
	'filter_alt',
	'grade',
	'group',
	'groups',
	'history',
	'history_edu',
	'insights',
	'label',
	'lock',
	'logout',
	'mail',
	'menu_book',
	'more_horiz',
	'pending_actions',
	'person_off',
	'power_settings_new',
	'print',
	'progress_activity',
	'refresh',
	'report',
	'save',
	'school',
	'search',
	'settings',
	'share',
	'star',
	'sync',
	'task_alt',
	'trending_up',
	'tune',
	'visibility',
	'visibility_off',
	'volunteer_activism',
	'warning',
	'wifi_off'
];

const SOURCES = [
	{
		name: 'Material Symbols Outlined',
		slug: 'material-symbols',
		url:
			'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200' +
			`&icon_names=${ICONS.join(',')}&display=block`
	},
	{
		name: 'IBM Plex Sans Arabic',
		slug: 'plex-arabic',
		url: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;400;500;600;700&display=swap'
	},
	{
		name: 'Plus Jakarta Sans',
		slug: 'jakarta',
		url: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap'
	}
];

async function fetchText(url) {
	const res = await fetch(url, { headers: { 'User-Agent': UA } });
	if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
	return res.text();
}

async function fetchBinary(url) {
	const res = await fetch(url, { headers: { 'User-Agent': UA } });
	if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
	return Buffer.from(await res.arrayBuffer());
}

/** Download every font referenced by a Google Fonts stylesheet, rewriting the
 *  `src: url(...)` to a local `/fonts/<file>` path. */
async function vendor(source) {
	const css = await fetchText(source.url);
	const urls = [...css.matchAll(/url\((https:\/\/[^)]+)\)/g)].map((m) => m[1]);
	const unique = [...new Set(urls)];

	// Keep only the @font-face rules. Google also ships a `.material-symbols-outlined`
	// helper class, but ours lives in app.css (with the project's weight/fill axes) and
	// must not be overridden.
	let out = (css.match(/@font-face\s*\{[^}]*\}/g) ?? []).join('\n\n');

	let index = 0;
	let bytes = 0;
	for (const remote of unique) {
		const file = `${source.slug}-${index++}.woff2`;
		const data = await fetchBinary(remote);
		await writeFile(join(OUT_DIR, file), data);
		bytes += data.length;
		out = out.split(remote).join(`/fonts/${file}`);
	}
	console.log(`  ${source.name}: ${unique.length} file(s), ${(bytes / 1024).toFixed(1)} KB`);
	return out;
}

async function main() {
	await mkdir(OUT_DIR, { recursive: true });
	console.log('Vendoring webfonts into static/fonts/ …');

	const blocks = [];
	for (const source of SOURCES) blocks.push(await vendor(source));

	const header = [
		'/* GENERATED by `npm run fonts` — do not edit by hand.',
		' *',
		' * Self-hosted webfonts. The app must never request a font over the network:',
		' * a missing icon font makes Material Symbols render their ligature *names* as',
		' * literal text (the spinner spins the word "progress_activity"), and a missing',
		' * Arabic font changes text metrics enough to overlap labels. See',
		' * scripts/fetch-fonts.mjs to add icons. */',
		''
	].join('\n');

	await writeFile(CSS_OUT, `${header}\n${blocks.join('\n')}`);
	console.log(`Wrote ${CSS_OUT}`);

	await writeFile(MANIFEST_OUT, `${JSON.stringify({ icons: ICONS }, null, '\t')}\n`);
	console.log(`Wrote ${MANIFEST_OUT} (${ICONS.length} icons)`);
}

await main();
