"""add parent summons and upcoming exams

Two new bounded contexts:

* ``parent_summons`` — «استدعاء ولي الأمر»: a teacher's request for the
  administration to call a guardian in, with its three-state workflow and the
  administration's reply back to the teacher.
* ``upcoming_exams`` — «الاختبار القادم»: a student's next planned examination.

Autogenerate additionally proposed dropping `server_default` from many existing
columns; that is pre-existing drift and is deliberately left out.

Revision ID: 1b37cd5065f0
Revises: faec17a7c449
Create Date: 2026-08-03 14:07:32.503993+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b37cd5065f0"
down_revision: str | None = "faec17a7c449"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parent_summons",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("halaqah_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("admin_response", sa.Text(), nullable=True),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["halaqah_id"],
            ["halaqahs.id"],
            name=op.f("fk_parent_summons_halaqah_id_halaqahs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_parent_summons_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_parent_summons_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parent_summons")),
    )
    op.create_index(
        op.f("ix_parent_summons_halaqah_id"), "parent_summons", ["halaqah_id"], unique=False
    )
    op.create_index(op.f("ix_parent_summons_status"), "parent_summons", ["status"], unique=False)
    op.create_index(
        op.f("ix_parent_summons_student_id"), "parent_summons", ["student_id"], unique=False
    )
    op.create_index(
        op.f("ix_parent_summons_teacher_id"), "parent_summons", ["teacher_id"], unique=False
    )
    op.create_table(
        "upcoming_exams",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("halaqah_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("part", sa.SmallInteger(), nullable=True),
        sa.Column("exam_from", sa.SmallInteger(), nullable=True),
        sa.Column("exam_to", sa.SmallInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "exam_from IS NULL OR exam_from >= 0",
            name=op.f("ck_upcoming_exams_exam_from_non_negative"),
        ),
        sa.CheckConstraint(
            "exam_to IS NULL OR exam_to >= 0", name=op.f("ck_upcoming_exams_exam_to_non_negative")
        ),
        sa.CheckConstraint(
            "part IS NULL OR part BETWEEN 1 AND 30", name=op.f("ck_upcoming_exams_part_range")
        ),
        sa.ForeignKeyConstraint(
            ["halaqah_id"],
            ["halaqahs.id"],
            name=op.f("fk_upcoming_exams_halaqah_id_halaqahs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_upcoming_exams_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_upcoming_exams_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upcoming_exams")),
    )
    op.create_index(
        op.f("ix_upcoming_exams_halaqah_id"), "upcoming_exams", ["halaqah_id"], unique=False
    )
    op.create_index(
        op.f("ix_upcoming_exams_scheduled_date"), "upcoming_exams", ["scheduled_date"], unique=False
    )
    op.create_index(op.f("ix_upcoming_exams_status"), "upcoming_exams", ["status"], unique=False)
    op.create_index(
        op.f("ix_upcoming_exams_student_id"), "upcoming_exams", ["student_id"], unique=False
    )
    op.create_index(
        op.f("ix_upcoming_exams_teacher_id"), "upcoming_exams", ["teacher_id"], unique=False
    )
def downgrade() -> None:
    op.drop_table("upcoming_exams")
    op.drop_table("parent_summons")
