"""add name to times

Revision ID: 3348fb60d838
Revises: 2ef8f12a721c
Create Date: 2026-06-18 08:37:48.492918+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3348fb60d838"
down_revision: str | None = "2ef8f12a721c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add NOT NULL with a temporary server_default to backfill existing rows,
    # then drop the default so future inserts must supply a name explicitly.
    op.add_column(
        "times",
        sa.Column("name", sa.String(length=150), nullable=False, server_default="وقت"),
    )
    op.alter_column("times", "name", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("times", "name")
    # ### end Alembic commands ###
