"""add daily_records table

Revision ID: 95e9a23c5d27
Revises: 3348fb60d838
Create Date: 2026-06-18 18:12:57.849325+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95e9a23c5d27"
down_revision: str | None = "3348fb60d838"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_records",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("halaqah_id", sa.Uuid(), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("exam_from", sa.SmallInteger(), nullable=True),
        sa.Column("exam_to", sa.SmallInteger(), nullable=True),
        sa.Column("exam_total", sa.SmallInteger(), nullable=True),
        sa.Column("homework", sa.Text(), nullable=True),
        sa.Column("problems", sa.Text(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("revision_lesson", sa.Text(), nullable=True),
        sa.Column("revision_rating", sa.SmallInteger(), nullable=True),
        sa.Column("attitude", sa.SmallInteger(), nullable=True),
        sa.Column("added_points", sa.SmallInteger(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("card_present", sa.SmallInteger(), nullable=False),
        sa.Column("card_exam", sa.SmallInteger(), nullable=False),
        sa.Column("card_attitude", sa.SmallInteger(), nullable=False),
        sa.Column("total_points", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "added_points >= 0", name=op.f("ck_daily_records_added_points_non_negative")
        ),
        sa.CheckConstraint(
            "attitude IS NULL OR attitude BETWEEN 1 AND 3",
            name=op.f("ck_daily_records_attitude_range"),
        ),
        sa.CheckConstraint(
            "exam_from IS NULL OR exam_from >= 0",
            name=op.f("ck_daily_records_exam_from_non_negative"),
        ),
        sa.CheckConstraint(
            "exam_to IS NULL OR exam_to >= 0", name=op.f("ck_daily_records_exam_to_non_negative")
        ),
        sa.CheckConstraint(
            "exam_total IS NULL OR exam_total >= 0",
            name=op.f("ck_daily_records_exam_total_non_negative"),
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating BETWEEN 1 AND 4", name=op.f("ck_daily_records_rating_range")
        ),
        sa.CheckConstraint(
            "revision_rating IS NULL OR revision_rating BETWEEN 1 AND 4",
            name=op.f("ck_daily_records_revision_rating_range"),
        ),
        sa.ForeignKeyConstraint(
            ["halaqah_id"],
            ["halaqahs.id"],
            name=op.f("fk_daily_records_halaqah_id_halaqahs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_daily_records_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_daily_records_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_records")),
        sa.UniqueConstraint("student_id", "record_date", name=op.f("uq_daily_records_student_id")),
    )
    op.create_index(
        op.f("ix_daily_records_halaqah_id"), "daily_records", ["halaqah_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_records_record_date"), "daily_records", ["record_date"], unique=False
    )
    op.create_index(
        op.f("ix_daily_records_student_id"), "daily_records", ["student_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_records_teacher_id"), "daily_records", ["teacher_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_records_teacher_id"), table_name="daily_records")
    op.drop_index(op.f("ix_daily_records_student_id"), table_name="daily_records")
    op.drop_index(op.f("ix_daily_records_record_date"), table_name="daily_records")
    op.drop_index(op.f("ix_daily_records_halaqah_id"), table_name="daily_records")
    op.drop_table("daily_records")
    # ### end Alembic commands ###
