"""initial schema

Revision ID: 2ef8f12a721c
Revises:
Create Date: 2026-06-17 21:05:36.362209+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ef8f12a721c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Linguistic (non-deterministic) ICU collation for sorting Arabic text.
    # Used at query time via ``.collate("arabic")`` for name/full_name ordering.
    op.execute(
        "CREATE COLLATION IF NOT EXISTS arabic "
        "(provider = icu, locale = 'ar', deterministic = false)"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "halaqah_types",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_halaqah_types")),
        sa.UniqueConstraint("name", name=op.f("uq_halaqah_types_name")),
    )
    op.create_table(
        "times",
        sa.Column("saturday", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sunday", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("monday", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tuesday", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("wednesday", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("thursday", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("friday", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_times")),
    )
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("super_admin", "teacher", name="user_role"), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "teachers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("academic_study", sa.String(length=255), nullable=False),
        sa.Column("islamic_study", sa.String(length=255), nullable=False),
        sa.Column("is_assistant", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_teachers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teachers")),
    )
    op.create_index(op.f("ix_teachers_user_id"), "teachers", ["user_id"], unique=True)
    op.create_table(
        "halaqahs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("halaqah_type_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.String(length=100), nullable=True),
        sa.Column("age", sa.String(length=100), nullable=True),
        sa.Column("time_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["halaqah_type_id"],
            ["halaqah_types.id"],
            name=op.f("fk_halaqahs_halaqah_type_id_halaqah_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_halaqahs_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["time_id"], ["times.id"], name=op.f("fk_halaqahs_time_id_times"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_halaqahs")),
    )
    op.create_index(
        op.f("ix_halaqahs_halaqah_type_id"), "halaqahs", ["halaqah_type_id"], unique=False
    )
    op.create_index(op.f("ix_halaqahs_teacher_id"), "halaqahs", ["teacher_id"], unique=False)
    op.create_index(op.f("ix_halaqahs_time_id"), "halaqahs", ["time_id"], unique=False)
    op.create_table(
        "students",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("father_name", sa.String(length=255), nullable=False),
        sa.Column("father_number", sa.String(length=40), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("mother_number", sa.String(length=40), nullable=True),
        sa.Column(
            "orphan_of", sa.Enum("father", "mother", "both", name="orphan_status"), nullable=True
        ),
        sa.Column("residential_area", sa.String(length=255), nullable=True),
        sa.Column("accepted_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("halaqah_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["halaqah_id"],
            ["halaqahs.id"],
            name=op.f("fk_students_halaqah_id_halaqahs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    op.create_index(op.f("ix_students_halaqah_id"), "students", ["halaqah_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_students_halaqah_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_halaqahs_time_id"), table_name="halaqahs")
    op.drop_index(op.f("ix_halaqahs_teacher_id"), table_name="halaqahs")
    op.drop_index(op.f("ix_halaqahs_halaqah_type_id"), table_name="halaqahs")
    op.drop_table("halaqahs")
    op.drop_index(op.f("ix_teachers_user_id"), table_name="teachers")
    op.drop_table("teachers")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("times")
    op.drop_table("halaqah_types")
    # ### end Alembic commands ###

    # Drop the native enum types and the Arabic collation created on upgrade.
    op.execute("DROP TYPE IF EXISTS orphan_status")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP COLLATION IF EXISTS arabic")
