"""add scoring_settings table

Revision ID: 886108024f77
Revises: 95e9a23c5d27
Create Date: 2026-06-19 11:49:37.612758+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "886108024f77"
down_revision: str | None = "95e9a23c5d27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoring_settings",
        sa.Column("present_points", sa.SmallInteger(), nullable=False),
        sa.Column("rating_4_points", sa.SmallInteger(), nullable=False),
        sa.Column("rating_3_points", sa.SmallInteger(), nullable=False),
        sa.Column("rating_2_points", sa.SmallInteger(), nullable=False),
        sa.Column("rating_1_points", sa.SmallInteger(), nullable=False),
        sa.Column("attitude_3_points", sa.SmallInteger(), nullable=False),
        sa.Column("attitude_2_points", sa.SmallInteger(), nullable=False),
        sa.Column("attitude_1_points", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scoring_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scoring_settings")
    # ### end Alembic commands ###
